### ISSUE TITLE
Getting rid of ref_url

### ISSUE THREAD

**Issue by kaguy4** [Heyuri/kokonotsuba#1]
Currently, links on heyuri have prefix _https://jump.heyuri.net/?_
It's defined at _define("REF_URL", 'https://jump.heyuri.net/%27);_ and setting it to blank breaks all links.

Therefore, I want to completely remove ref_url

**Comment by notACXYZ** [comment]
What if we just change it so it works with a blank input like this?

```php
/* 網址自動連結 */
function auto_link_callback2($matches){
	$URL = $matches[1].$matches[2]; // https://example.com
	$URL_Encode = urlencode($URL);  // https%3A%2F%2Fexample.com 

	// Redirect URL!
	if (REF_URL) {
		return '<a href="'.REF_URL.'?'.$URL_Encode.'" target="_blank" rel="nofollow noreferrer">'.$URL.'</a>';
	}
	// Also works if its blank!
	return '<a href="'.$URL.'" target="_blank" rel="nofollow noreferrer">'.$URL.'</a>';
}
```

**Comment by kaguy4** [comment]
> What if we just change it so it works with a blank input like this?
> 
> (Line 173 at /lib/lib_common.php):
> 
> ```
> /* 網址自動連結 */
> function auto_link_callback2($matches) {
> 	$URL = $matches[1].$matches[2]; // https://example.com
> 
> 	// Redirect URL!
> 	if (REF_URL) {
> 		$URL_Encode = urlencode($URL);  // https%3A%2F%2Fexample.com (For the address bar)
> 		return '<a href="'.REF_URL.'?'.$URL_Encode.'" target="_blank" rel="nofollow noreferrer">'.$URL.'</a>';
> 	}
> 	// Also works if its blank!
> 	return '<a href="'.$URL.'" target="_blank" rel="nofollow noreferrer">'.$URL.'</a>';
> }
> ```

That works perfectly, thanks!
