### ISSUE TITLE
[feature] More fortunes

### ISSUE THREAD

**Issue by mitaka78** [Heyuri/kokonotsuba#14]
From [this](
https://img.heyuri.net/q/koko.php?res=62319) /q/ thread, we can see that a good portion of users would like more fortunes 

and some people on [this](
https://img.heyuri.net/q/koko.php?res=62319) /b/ thread also talked about there not being enough fortunes & them being more negative overall

I am aware that pretty much every1 has seen the thread, but just leaving it here for more organisation

**Comment by kaguy4** [comment]
Added these to /b/, so closing. You can still make pull requests for other (new) fortunes if you want to
