### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by mitaka78** [Heyuri/kokonotsuba#15]
It might be good to add issue templates, so users can post about their issue/feature/whatever more efficiently and organized - and issue templates apply labels, so it's also a workaround to users being unable to apply labels

**Comment by kaguy4** [comment]
I added 3 for bug reports, help requests and feature ideas (ﾟｰﾟ)
I don't think we really need enforce a specific template for posts, so their templates are rather vague on purpose

**Comment by mitaka78** [comment]
good idea :P
