### ISSUE TITLE
Currently X unique users on this board

### ISSUE THREAD

**Issue by kaguy4** [Heyuri/kokonotsuba#26]
We used to have this, it's similar to what the script on Strange World has.

Preferably It should be at addinfo like it used to be - Between boku and bbcode reference, but I don't know if that's doable because starting from "Read the rules before you post." until the boku, it's showing from a static file.

**Comment by D4di69** [comment]
![ohno](https://github.com/Heyuri/kokonotsuba/assets/99908436/7b605259-cfc4-496c-ab65-8010d43acd41)

**Comment by kaguy4** [comment]
O_o
