### ISSUE TITLE
Overboard (view posts from all kokonotsuba boards on a single page)

### ISSUE THREAD

**Issue by anonwaha** [Heyuri/kokonotsuba#27]
Before kokonotsuba, Heyuri's previous software had an overboard feature (also known as /all/). It was like a regular board index, but it would show posts from every board all in one place - it would show threads as the OP and the last couple of replies (if any), sorted by latest post/reply first (and ignoring sage)

Here's what it looked like (PS: there's more below the image):
![Screen Shot 2020-09-09 at 11 54 03-fullpage](https://user-images.githubusercontent.com/122128562/213160817-06a9ff84-108f-47c8-a2f8-6b444177f3b5.png)

It also had a feature added to it so that you could filter out specific boards from the overboard using checkboxes. Back then you had to set the filters every time you visited, but it might be better if it used cookies/local storage to save the user's settings

Here's what that looked like when opened:
![overboard board filters](https://user-images.githubusercontent.com/122128562/213161533-4d71e349-0f2c-48c4-b036-2bcb18eac4a1.png)

**Comment by kaguy4** [comment]
Done ヽ(´ー｀)ノ
https://github.com/hachikuji-san/koko-overboard/
