### ISSUE TITLE
Switch form position (move post form to bottom of thread)

### ISSUE THREAD

**Issue by anonwaha** [Heyuri/kokonotsuba#28]
Kokonotsuba (and previous Heyuri software) used to have a JavaScript feature to move the post form to the bottom of the page. You would click a link that said "Switch Form Position", and the post form would instantly move to the bottom of the thread beneath the replies, as well as jumping the user down there. This was convenient for replying to the latest replies without using quick reply

Here's what the link looked like on the previous software:
![swtich form position](https://user-images.githubusercontent.com/122128562/213177727-13dd4f08-8860-467e-801d-85002938f487.png)

And here's what the post form looked like after clicking it (there are some minor CSS errors due to the archive I used for the screencap being incomplete, but you get the idea):
![switched form position](https://user-images.githubusercontent.com/122128562/213215571-592c817e-3503-4d89-a0c6-8210c7811ced.png)

I don't know if it helps, but you can find the JS for the previous software here - I think the relevant section is `formSwitch()`:
https://2ch.sh/src/2614.js

**Comment by kaguy4** [comment]
restored ヽ(´ー｀)ノ
