### ISSUE TITLE
"ERROR: Cannot write to SOUDANE_DIR!"

### ISSUE THREAD

**Issue by planetzeke** [Heyuri/kokonotsuba#35]
This happened when i tried to install  koko
<img width="2130" alt="Screenshot 2023-01-24 at 7 43 54 PM" src="https://user-images.githubusercontent.com/118635655/214454801-472f7750-8892-4ca4-a440-62c794ef3826.png">

**Comment by notACXYZ** [comment]
You need to give that folders permission to read and write. 

- Unix, chmod 755.
- Mac, give sharing & permission on Everybody to 'Read and Write' and select Apply to enclosed items.
- On Windows, do the same thing like in Mac minus the last step.
