### ISSUE TITLE
Bring back Field Traps

### ISSUE THREAD

**Issue by notACXYZ** [Heyuri/kokonotsuba#36]
Previously on Pixmicat, it was a feature there to catch automated spam while letting users post normally.
What's weird is that this feature got removed entirely from Koko in favour of KolymaNET's SpamDB.

Restoring this feature will bring added security to the post form.

Former settings in `config.php`
```php
/*---- Part 3：Anti-Spam Field Trap ----*/
define("FT_NAME", 'bvUFbdrIC'); // Name
define("FT_EMAIL", 'ObHGyhdTR'); // E-mail
define("FT_SUBJECT", 'SJBgiFbhj'); // Title
define("FT_COMMENT", 'pOBvrtyJK'); // Comment
```
It was also formerly featured in `/lib/lib_commmon.php` and `koko.php` but replaced with normal values.

What do you think?

**Comment by kaguy4** [comment]
I think it's good to have on github version
