### ISSUE TITLE
Cannot login as admin, mod, or janitor

### ISSUE THREAD

**Issue by RealAngeleno** [Heyuri/kokonotsuba#4]
Environment:
Everything within the kokonotsuba folder is owned by www-data (which may be a security risk, but this is for testing)
PHP 7.2
Apache/2.4.29 (Ubuntu)

When attempting to log into the admin panel (using the password set in "ADMIN_HASH", the page simply refreshes in the same way an incorrect password does.

Enabling display_errors does not show anything.

**Comment by kuz-sysadmin** [comment]
https://sys.kolyma.net/passwd.php

**Comment by RealAngeleno** [comment]
This worked. Thanks kuz.
