### ISSUE TITLE
Remove "Powered by Kolyma" on kokotxt.tpl

### ISSUE THREAD

**Issue by RealAngeleno** [Heyuri/kokonotsuba#42]
I think that the "Powered by Kolyma" image (line 75) on kokotxt.tpl should be removed. Since if you're running your own server on a different server provider and have zero relations to Kolyma, your server isn't really powered by Kolyma anymore. Similar to how if you ran a Futabawall instance, it wouldn't be "powered by Futaba Channel." Credit to KolymaNET could be moved to the footer similar to how it is mandated to credit Heyuri.

Maybe a "Powered by Kokonotsuba" image?

**Comment by kaguy4** [comment]
I won't close this as someone may come up with the mentioned "Powered by Kokonotsuba" image, but I think the credits at footer are already enough

**Comment by kaguy4** [comment]
Guess noone will...
