### ISSUE TITLE
Spam "Vulnerability"?

### ISSUE THREAD

**Issue by mizunforest** [Heyuri/kokonotsuba#45]
Unsure what to put this as but Kokonotsuba is very easily spammed. All you need to do to spam it easily is to open inspect element, navigate to the "Network" tab, make a post, edit and resend the post request then spam it. Not sure what could necessarily be done to fix this but I thought it would be better to let you all know.

![image](https://user-images.githubusercontent.com/127715009/224612249-0bb74bbb-e9dc-41f4-bad3-fb95b0f2db7c.png)

**Comment by RealAngeleno** [comment]
Many other IBs simply use a post cooldown to prevent you from doing this. Can reproduce easily on futaba-eki, a completely different imageboard software, by disabling the post cooldown then clicking the post button a bunch of times.

**Comment by D4di69** [comment]
lol

**Comment by chen-chan1** [comment]
i mean i guess we all know this is a issue, this is something that should be handled out side of koko? or maybe a have better rate limit.

over the last year i keep re opening this issue over and over and see it as a meme. this is something cloudflare/kiwiflare protects.
and normal users who abuse this will obvious see ban.

i mean this is more over a http/ip issue then a php code issue in my opinion

**Comment by kaguy4** [comment]
I'll take ur word
