### ISSUE TITLE
Post searching should be case-insensitive

### ISSUE THREAD

**Issue by kaguy4** [Heyuri/kokonotsuba#72]
Currently it's case-sensitive, it should be case-insensitive

Bonus 1: I think the searching function is not a module now - if possible, it should be a module instead of hard coded in koko.php
Bonus 2: Case-sensitive search can still be left off as an option for searching

**Comment by chen-chan1** [comment]
this seems like it has been added. i assume for hachi merge and since this works in JS.  unless you meant for each post to be search and no OP

**Comment by kaguy4** [comment]
I was thinking of
>Case-sensitive search can still be left off as an option for searching
But well, it's not a big issue. Closing
